# Generated by Django 3.0.4 on 2020-03-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.department'),
        ),
    ]
